version: '3.8'
services:
  db:
    image: postgres:15
    container_name: supabase-db
    restart: always
    environment:
      POSTGRES_USER: gabrielbritop
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data:
